domain_admin_group_sid = 502
max_ticket_lifetime_hours = 1000
event_ids = [ 4769, 4769, 4769, 4769, 4769, 4769, 4769, 4769, 4769, 4769 ]
user_rids = [ 500, 501, 502, 512, 513, 518, 519, 520, 521, 522 ]
group_membership = [ 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009 ]
ticket_lifetimes = [ 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009 ]
_timestamps = [ 123, 123, 123, 123, 123, 123, 123, 123, 123, 123 ]
